name: Display CPU and Memory Usage
on:
  push:
    branches:
       - main
  
jobs: 
 display_metrics: 
  runs-on: self-hosted

  steps:
  - name: checkout code
    uses: actions/checkout@v2

  - name: Install Python3
    run: |
       sudo apt install -y python3
    
  - name: Install required Python packages
    run: |
       python3 -m pip install Flask  

  - name: Install required python packages
    run: |
       python3 -m pip install psutil

  - name: Start a simple HTTP server for index.html
    run: |
      python3 -m http.server 5321
    shell: bash
