name: Display CPU and Memory Usage
on:
  push:
    branches:
       - main
  
jobs: 
 display_metrics: 
  runs-on: self-hosted

  steps:
  - name: checkout code
    uses: actions/checkout@v2

  - name: Install Python3
    run: |
       sudo apt install -y python3
    
  - name: Install required Python packages
    run: |
       python3 -m pip install Flask  
       python3 -m pip install psutil

  - name: Set Template Directory  
    run: echo "TEMPLATE_DIR=templates" >> $GITHUB_ENV

  - name: Start HTTP server for index.html      
    run: python3 -m http.server -d ${{ env.TEMPLATE_DIR }}
    
  - name: Run app.py
    run: |
       python src/app.py

 
