name: Display CPU and Memory Usage
on:
  push:
    branches:
       - main
  
jobs: 
 display_metrics: 
  runs-on: self-hosted

  steps:
  - name: checkout code
    uses: actions/checkout@v2

  - name: Install Python3
    run: |
      sudo apt update
      sudo apt install -y python3
    shell: bash

  - name: Install required Python packages
    run: |
       python3 -m pip install Flask 
    shell: bash

  - name: Install required python packages
    run: |
       python3 -m pip install psutil
    shell: bash
    
  - name: Run app.py in the background
    run: |
      nohup python3 app.py & 
    shell: bash
    #background: true

  - name: Start a simple HTTP server for index.html
    run: |
      python3 -m http.server 5321
    shell: bash
    #background: true
